import os
from datetime import date
from decimal import Decimal
from fpdf import FPDF
from sqlalchemy.orm import Session
from app.models.models import User, Trade, DailyPnL, AISuggestion, AuditLog

class PDFReport(FPDF):
    def __init__(self, title_text: str, subtitle_text: str):
        super().__init__()
        self.title_text = title_text
        self.subtitle_text = subtitle_text

    def header(self):
        # Header banner (Slate Blue)
        self.set_fill_color(30, 41, 59)
        self.rect(0, 0, 210, 25, "F")
        
        # Title
        self.set_xy(10, 6)
        self.set_font("helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, self.title_text, align="L")
        
        # Subtitle
        self.set_xy(10, 13)
        self.set_font("helvetica", "", 10)
        self.set_text_color(203, 213, 225)  # Light slate
        self.cell(0, 5, self.subtitle_text, align="L")
        
        self.set_y(30)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184)  # Slate 400
        # Line divider
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_y(-12)
        self.cell(0, 10, f"Generated by PyramidStrategy - Page {self.page_no()}/{{nb}}", align="C")

def build_daily_report_pdf(user_id: int, target_date: date, db: Session, output_path: str):
    """
    Generate a beautifully styled daily PDF report.
    """
    user = db.query(User).filter(User.id == user_id).first()
    username = user.username if user else f"User {user_id}"
    date_str = target_date.strftime("%d-%b-%Y")

    # Fetch stats
    daily_pnl = db.query(DailyPnL).filter(
        DailyPnL.user_id == user_id,
        DailyPnL.trade_date == target_date
    ).first()

    trades = db.query(Trade).filter(
        Trade.user_id == user_id,
        Trade.trade_date == target_date
    ).order_by(Trade.created_at.asc()).all()

    audit_logs = db.query(AuditLog).filter(
        AuditLog.user_id == user_id,
        AuditLog.created_at >= target_date,
        AuditLog.created_at < target_date + __import__("datetime").timedelta(days=1)
    ).order_by(AuditLog.created_at.asc()).all()

    ai_suggestions = db.query(AISuggestion).filter(
        AISuggestion.user_id == user_id,
        AISuggestion.trade_date == target_date
    ).order_by(AISuggestion.created_at.asc()).all()

    # Calculate metrics if daily_pnl is not synced/updated yet
    if daily_pnl:
        gross_pnl = daily_pnl.gross_pnl
        brokerage = daily_pnl.brokerage
        net_pnl = daily_pnl.net_pnl
        total_trades = daily_pnl.total_trades
        winning_trades = daily_pnl.winning_trades
        ce_pnl = daily_pnl.ce_pnl
        pe_pnl = daily_pnl.pe_pnl
    else:
        exits = [t for t in trades if t.action == "EXIT"]
        gross_pnl = sum((t.pnl for t in exits if t.pnl is not None), Decimal("0"))
        total_trades = len(trades)
        brokerage = Decimal(str(total_trades * 20.0))
        net_pnl = gross_pnl - brokerage
        winning_trades = sum(1 for t in exits if t.pnl is not None and t.pnl > 0)
        ce_exits = [t for t in exits if t.side == "CE"]
        pe_exits = [t for t in exits if t.side == "PE"]
        ce_pnl = sum((t.pnl for t in ce_exits if t.pnl is not None), Decimal("0"))
        pe_pnl = sum((t.pnl for t in pe_exits if t.pnl is not None), Decimal("0"))

    losing_trades = max(0, sum(1 for t in trades if t.action == "EXIT") - winning_trades)

    pdf = PDFReport(
        title_text=f"PyramidStrategy Daily EOD Report",
        subtitle_text=f"Trader: {username}  |  Date: {date_str}  |  Platform: Kite Connect"
    )
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("helvetica", "", 10)

    # 1. P&L Overview Cards
    pdf.set_fill_color(248, 250, 252) # Light background
    pdf.rect(10, 32, 190, 35, "F")
    
    # Net P&L display with custom color
    pdf.set_xy(15, 36)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(50, 5, "Net P&L (Estimated)")
    
    pdf.set_xy(15, 43)
    pdf.set_font("helvetica", "B", 24)
    if net_pnl >= 0:
        pdf.set_text_color(16, 185, 129)  # Emerald 500
        sign = "+"
    else:
        pdf.set_text_color(239, 68, 68)   # Red 500
        sign = ""
    pdf.cell(70, 10, f"{sign}Rs. {net_pnl:,.2f}")
    
    # Stats Breakdown Column
    pdf.set_text_color(71, 85, 105)
    pdf.set_font("helvetica", "", 10)
    
    pdf.set_xy(95, 36)
    pdf.cell(50, 5, f"Gross P&L: Rs. {gross_pnl:,.2f}")
    pdf.set_xy(95, 43)
    pdf.cell(50, 5, f"Est. Brokerage: Rs. {brokerage:,.2f}")
    pdf.set_xy(95, 50)
    pdf.cell(50, 5, f"Total Orders: {total_trades}")
    
    pdf.set_xy(150, 36)
    pdf.cell(50, 5, f"Winning Exits: {winning_trades}")
    pdf.set_xy(150, 43)
    pdf.cell(50, 5, f"Losing Exits: {losing_trades}")
    pdf.set_xy(150, 50)
    pdf.cell(50, 5, f"Win Rate: {(winning_trades / (winning_trades + losing_trades) * 100 if (winning_trades + losing_trades) > 0 else 0.0):.1f}%")

    # 2. Leg Breakdown (CE vs PE)
    pdf.set_xy(10, 75)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Leg Performance Breakdown")
    pdf.ln(8)
    
    # Table headers
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(45, 7, "Leg Side", 1, 0, "C", True)
    pdf.cell(45, 7, "Gross P&L", 1, 0, "C", True)
    pdf.cell(50, 7, "Net P&L (Est.)", 1, 0, "C", True)
    pdf.cell(50, 7, "Trade Volume", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    # CE Row
    pdf.cell(45, 7, "Call Option (CE)", 1, 0, "C")
    pdf.cell(45, 7, f"Rs. {ce_pnl:,.2f}", 1, 0, "R")
    ce_net = ce_pnl - Decimal(str(sum(1 for t in trades if t.side == "CE") * 20.0))
    pdf.cell(50, 7, f"Rs. {ce_net:,.2f}", 1, 0, "R")
    pdf.cell(50, 7, f"{sum(1 for t in trades if t.side == 'CE')} executions", 1, 1, "C")

    # PE Row
    pdf.cell(45, 7, "Put Option (PE)", 1, 0, "C")
    pdf.cell(45, 7, f"Rs. {pe_pnl:,.2f}", 1, 0, "R")
    pe_net = pe_pnl - Decimal(str(sum(1 for t in trades if t.side == "PE") * 20.0))
    pdf.cell(50, 7, f"Rs. {pe_net:,.2f}", 1, 0, "R")
    pdf.cell(50, 7, f"{sum(1 for t in trades if t.side == 'PE')} executions", 1, 1, "C")

    # 3. Trades Executed
    pdf.ln(6)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Executions / Trade Log")
    pdf.ln(8)
    
    # Table headers
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(20, 7, "Time", 1, 0, "C", True)
    pdf.cell(45, 7, "Instrument", 1, 0, "C", True)
    pdf.cell(20, 7, "Action", 1, 0, "C", True)
    pdf.cell(20, 7, "Lots", 1, 0, "C", True)
    pdf.cell(25, 7, "Avg Price", 1, 0, "C", True)
    pdf.cell(30, 7, "P&L Status", 1, 0, "C", True)
    pdf.cell(30, 7, "Nifty Trigger", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    if not trades:
        pdf.cell(190, 8, "No trades executed today.", 1, 1, "C")
    else:
        for t in trades:
            time_str = t.created_at.strftime("%I:%M %p") if t.created_at else ""
            pdf.cell(20, 7, time_str, 1, 0, "C")
            pdf.cell(45, 7, t.instrument, 1, 0, "C")
            
            # Action styling
            if t.action == "BUY":
                pdf.set_text_color(16, 185, 129)
                action_text = "BUY"
            else:
                pdf.set_text_color(239, 68, 68)
                action_text = f"EXIT"
            pdf.cell(20, 7, action_text, 1, 0, "C")
            pdf.set_text_color(30, 41, 59) # reset
            
            pdf.cell(20, 7, str(t.lots), 1, 0, "C")
            pdf.cell(25, 7, f"Rs. {t.avg_price:.2f}", 1, 0, "R")
            
            pnl_val = t.pnl if t.pnl is not None else Decimal("0")
            if t.action == "EXIT":
                pnl_color = (16, 185, 129) if pnl_val >= 0 else (239, 68, 68)
                pdf.set_text_color(*pnl_color)
                pdf.cell(30, 7, f"{'+' if pnl_val >= 0 else ''}Rs. {pnl_val:,.2f} ({t.status})", 1, 0, "C")
            else:
                pdf.cell(30, 7, "-", 1, 0, "C")
            pdf.set_text_color(30, 41, 59) # reset
            
            pdf.cell(30, 7, f"{t.trigger_nifty_level:.2f}" if t.trigger_nifty_level else "-", 1, 1, "C")

    # 4. Strategy Decisions (Audit Log)
    pdf.ln(6)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Strategy Decisions & Rule Triggers")
    pdf.ln(8)
    
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(20, 7, "Time", 1, 0, "C", True)
    pdf.cell(40, 7, "Event", 1, 0, "C", True)
    pdf.cell(25, 7, "Side/Level", 1, 0, "C", True)
    pdf.cell(25, 7, "Nifty Price", 1, 0, "C", True)
    pdf.cell(80, 7, "Details/Reasoning", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 8)
    if not audit_logs:
        pdf.cell(190, 8, "No strategy rule triggers logged today.", 1, 1, "C")
    else:
        for log in audit_logs:
            time_str = log.created_at.strftime("%I:%M:%S %p") if log.created_at else ""
            pdf.cell(20, 7, time_str, 1, 0, "C")
            pdf.cell(40, 7, log.event_type, 1, 0, "C")
            pdf.cell(25, 7, f"{log.side or ''} {log.level or ''}".strip() or "-", 1, 0, "C")
            pdf.cell(25, 7, f"{log.nifty_price:.2f}" if log.nifty_price else "-", 1, 0, "C")
            
            # Details string extraction
            details_str = ""
            if log.details:
                if "msg" in log.details:
                    details_str = log.details["msg"]
                elif "reason" in log.details:
                    details_str = f"Reason: {log.details['reason']}"
                else:
                    details_str = str(log.details)[:60]
            else:
                details_str = "-"
            pdf.cell(80, 7, details_str[:55], 1, 1, "L")

    # 5. AI Observations
    pdf.ln(6)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "AI Observations & Trade Guidance")
    pdf.ln(8)
    
    if not ai_suggestions:
        pdf.set_font("helvetica", "I", 9)
        pdf.cell(0, 6, "No AI suggestions or observations recorded today.", 0, 1)
    else:
        for sugg in ai_suggestions:
            pdf.set_fill_color(241, 245, 249)
            pdf.set_font("helvetica", "B", 9)
            time_str = sugg.created_at.strftime("%I:%M %p") if sugg.created_at else ""
            pdf.cell(0, 6, f"  Robot Observer | {sugg.event} ({sugg.side or 'General'}) at {time_str} | Nifty: {sugg.nifty_ltp or '-'}", 0, 1, "L", True)
            
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(51, 65, 85)
            # Wrap suggestion inside multi_cell
            pdf.multi_cell(0, 5, sugg.suggestion)
            pdf.ln(3)
            pdf.set_text_color(30, 41, 59)

    # Save to file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path

def build_weekly_report_pdf(user_id: int, monday_date: date, db: Session, output_path: str):
    """
    Generate a beautifully styled weekly summary briefing PDF.
    """
    user = db.query(User).filter(User.id == user_id).first()
    username = user.username if user else f"User {user_id}"
    
    start_date = monday_date - __import__("datetime").timedelta(days=7)
    end_date = monday_date - __import__("datetime").timedelta(days=3)
    
    start_str = start_date.strftime("%d-%b")
    end_str = end_date.strftime("%d-%b")
    
    # Fetch weekly data
    daily_pnls = db.query(DailyPnL).filter(
        DailyPnL.user_id == user_id,
        DailyPnL.trade_date >= start_date,
        DailyPnL.trade_date <= end_date
    ).order_by(DailyPnL.trade_date.asc()).all()

    total_gross = sum((p.gross_pnl for p in daily_pnls), Decimal("0"))
    total_brokerage = sum((p.brokerage for p in daily_pnls), Decimal("0"))
    total_net = sum((p.net_pnl for p in daily_pnls), Decimal("0"))
    total_trades = sum((p.total_trades for p in daily_pnls), 0)
    total_wins = sum((p.winning_trades for p in daily_pnls), 0)
    ce_total_pnl = sum((p.ce_pnl for p in daily_pnls), Decimal("0"))
    pe_total_pnl = sum((p.pe_pnl for p in daily_pnls), Decimal("0"))
    
    active_days = len(daily_pnls)
    winning_days = sum(1 for p in daily_pnls if p.net_pnl > 0)
    win_rate_days = (winning_days / active_days * 100) if active_days > 0 else 0.0

    pdf = PDFReport(
        title_text=f"PyramidStrategy Weekly Trading Report",
        subtitle_text=f"Trader: {username}  |  Week: {start_str} to {end_str}  |  Weekly Briefing"
    )
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("helvetica", "", 10)

    # 1. Weekly Performance Summary Cards
    pdf.set_fill_color(248, 250, 252) # Light background
    pdf.rect(10, 32, 190, 35, "F")
    
    pdf.set_xy(15, 36)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(50, 5, "Net Weekly P&L")
    
    pdf.set_xy(15, 43)
    pdf.set_font("helvetica", "B", 24)
    if total_net >= 0:
        pdf.set_text_color(16, 185, 129)  # Emerald 500
        sign = "+"
    else:
        pdf.set_text_color(239, 68, 68)   # Red 500
        sign = ""
    pdf.cell(70, 10, f"{sign}Rs. {total_net:,.2f}")
    
    pdf.set_text_color(71, 85, 105)
    pdf.set_font("helvetica", "", 10)
    
    pdf.set_xy(95, 36)
    pdf.cell(50, 5, f"Gross Weekly P&L: Rs. {total_gross:,.2f}")
    pdf.set_xy(95, 43)
    pdf.cell(50, 5, f"Est. Brokerage: Rs. {total_brokerage:,.2f}")
    pdf.set_xy(95, 50)
    pdf.cell(50, 5, f"Total Executed: {total_trades} orders")
    
    pdf.set_xy(150, 36)
    pdf.cell(50, 5, f"Profit Days: {winning_days} of {active_days}")
    pdf.set_xy(150, 43)
    pdf.cell(50, 5, f"Winning Trades: {total_wins}")
    pdf.set_xy(150, 50)
    pdf.cell(50, 5, f"Daily Win Rate: {win_rate_days:.1f}%")

    # 2. CE vs PE Side Performance
    pdf.set_xy(10, 75)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Option Side Performance")
    pdf.ln(8)
    
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(60, 7, "Leg Side", 1, 0, "C", True)
    pdf.cell(65, 7, "Total Gross P&L", 1, 0, "C", True)
    pdf.cell(65, 7, "Share of Activity", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    # CE
    pdf.cell(60, 7, "Call Options (CE)", 1, 0, "C")
    pdf.cell(65, 7, f"Rs. {ce_total_pnl:,.2f}", 1, 0, "R")
    ce_pct = (ce_total_pnl / (abs(ce_total_pnl) + abs(pe_total_pnl)) * 100) if (abs(ce_total_pnl) + abs(pe_total_pnl)) > 0 else 50.0
    pdf.cell(65, 7, f"{ce_pct:.1f}% of Leg P&L", 1, 1, "C")
    
    # PE
    pdf.cell(60, 7, "Put Options (PE)", 1, 0, "C")
    pdf.cell(65, 7, f"Rs. {pe_total_pnl:,.2f}", 1, 0, "R")
    pe_pct = 100.0 - ce_pct
    pdf.cell(65, 7, f"{pe_pct:.1f}% of Leg P&L", 1, 1, "C")

    # 3. Daily Breakdown Table
    pdf.ln(6)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Daily P&L Performance Breakdown")
    pdf.ln(8)
    
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(30, 7, "Date", 1, 0, "C", True)
    pdf.cell(30, 7, "Day", 1, 0, "C", True)
    pdf.cell(30, 7, "Gross P&L", 1, 0, "C", True)
    pdf.cell(30, 7, "Brokerage", 1, 0, "C", True)
    pdf.cell(35, 7, "Net P&L", 1, 0, "C", True)
    pdf.cell(35, 7, "Trades count", 1, 1, "C", True)

    pdf.set_font("helvetica", "", 9)
    if not daily_pnls:
        pdf.cell(190, 8, "No trading activity recorded for last week.", 1, 1, "C")
    else:
        for p in daily_pnls:
            pdf.cell(30, 7, p.trade_date.strftime("%d-%b"), 1, 0, "C")
            pdf.cell(30, 7, p.trade_date.strftime("%A"), 1, 0, "C")
            pdf.cell(30, 7, f"Rs. {p.gross_pnl:,.2f}", 1, 0, "R")
            pdf.cell(30, 7, f"Rs. {p.brokerage:,.2f}", 1, 0, "R")
            
            pnl_color = (16, 185, 129) if p.net_pnl >= 0 else (239, 68, 68)
            pdf.set_text_color(*pnl_color)
            pdf.cell(35, 7, f"{'+' if p.net_pnl >= 0 else ''}Rs. {p.net_pnl:,.2f}", 1, 0, "R")
            pdf.set_text_color(30, 41, 59)
            
            pdf.cell(35, 7, f"{p.total_trades} orders", 1, 1, "C")

    # Save to file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
